### ISSUE TITLE
Create a Readme for the project.

### ISSUE THREAD

**Issue by Divya10** [jboss-outreach/certifier#7]

**Comment by opticod** [comment]
Write a short description about the project. You can start by giving the introduction of the game.

You can refer this for help:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by opticod** [comment]
Write a short description about the project. You can start by giving the introduction of the project.

You can refer this for help:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
